#!/usr/bin/env sh
set -eu
repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
GOTOOLCHAIN=auto GOCACHE=/tmp/ztb-z11-chaincode-cache go -C "$repo_root/chaincode" test -count=1 -v ./...
GOTOOLCHAIN=auto GOCACHE=/tmp/ztb-z11-gateway-cache go -C "$repo_root/gateway" test -count=1 ./...
